title: "Caravan (Catchment Attributes and Meteorology for Large-sample Studies) - A global community dataset for large-sample hydrology"
description: >
  Caravan is an open community dataset of meteorological forcing data, catchment attributes, and discharge data for catchments around the world. Additionally, Caravan provides code to derive meteorological forcing data and catchment attributes from the same data sources in the cloud, making it easy for anyone to extend Caravan to new catchments. The vision of Caravan is to provide the foundation for a truly global open source community resource that will grow over time. https://www.nature.com/articles/s41597-023-01975-w
provenance:
  providers:
    - name: "Zendodo"
      description: "https://zenodo.org/records/15529786"
      version: "1.6"
      roles:
        - distributor
        - licensor
  license: "CC 4.0"
maintainers:
  - name: "Raphael Hagen"
    github: norlandrhagen
  - name: "Kara D. Lamb"
    github: "<ADD>"
    orcid: "<optional:ADD>"
  - name: "Samarth Agrawal"
    github: "SammyAgrawal"
    orcid: "<optional:ADD>"
